### ISSUE TITLE
Parameter that exists appears not to exist

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#394] opened 2020-09-09 17:23 UTC
Alright, that's not a good or clear issue title, but I'm not sure what to make of this one.

I have an example where I have defined a parameter, but nlmixr says that it doesn't exist.  I tried running the model twice, and there appeared to be something unusual happening with caching, too.  I'm not sure why `v` is said not to exist below.

(I'm using current versions of pruneBranch and foceiDur as of yesterday.  Perhaps some of your optimization fixes from yesterday could help here, too.  If so, I'll update and retry.)

``` r
library(nlmixr)

one.cmt <- function() {
  ini({
    ## You may label each parameter with a comment
    tka <- 0.45 # Log Ka
    tcl <- 1 # Log Cl
    ## This works with interactive models
    ## You may also label the preceding line with label("label text")
    tv <- 3.45; label("log V")
    ## the label("Label name") works with all models
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    vx <- v
    linCmt() ~ add(add.sd)
  })
}

one.cmt_u <- update(one.cmt)
#> i parameter labels from comments will be replaced by 'label()'
class(one.cmt_u)
#> [1] "nlmixrUI"
fit <- nlmixr(one.cmt, theo_sd, est="focei", control=foceiControl(print=0))
#> i parameter labels from comments will be replaced by 'label()'
#> > creating full model...
#> > pruning branches (`if`/`else`)...
#> v done
#> > loading into symengine environment...
#> v done
#> > creating full model...
#> > pruning branches (`if`/`else`)...
#> v done
#> > loading into symengine environment...
#> v done
#> > calculate jacobian
#> > calculate d(f)/d(eta)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> > calculate d(R^2)/d(eta)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> > finding duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> > optimizing duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> > finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> > optimizing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> > compiling inner model...
#> v done
#> > compiling EBE model...
#> v done
#> RxODE 0.9.2.0 using 4 threads (see ?getRxThreads)
#> calculating covariance matrix
#> done
#> Calculating residuals/tables
#> Model:
#> 
#> rx_yj_~2;
#> rx_lambda_~1;
#> rx_hi_~1;
#> rx_low_~0;
#> rx_expr_0~ETA[2]+THETA[2];
#> rx_expr_1~ETA[3]+THETA[3];
#> rx_expr_2~ETA[1]+THETA[1];
#> rx_expr_3~exp(rx_expr_0);
#> rx_expr_4~exp(rx_expr_1);
#> rx_expr_5~exp(rx_expr_2);
#> rx_pred_=linCmtB(rx__PTR__,t,0,1,1,0,rx_expr_3,rx_expr_4,0,0,0,0,0,1,0,0,rx_expr_5,0,1,0,0);
#> rx_r_=((THETA[4])*(THETA[4]));
#> tka=THETA[1];
#> tcl=THETA[2];
#> tv=THETA[3];
#> add.sd=THETA[4];
#> eta.ka=ETA[1];
#> eta.cl=ETA[2];
#> eta.v=ETA[3];
#> vx=v;
#> ka=rx_expr_5;
#> cl=rx_expr_3;
#> v=rx_expr_4;
#> vx=rx_expr_4;
#> tad=tad();
#> dosenum=dosenum();
#> Error in rxSolveSEXP(object, .ctl, .nms, .xtra, params, events, inits, : The following parameter(s) are required for solving: v
fit <- nlmixr(one.cmt, theo_sd, est="focei", control=foceiControl(print=0))
#> i parameter labels from comments will be replaced by 'label()'
#> calculating covariance matrix
#> done
#> Calculating residuals/tables
#> Model:
#> 
#> rx_yj_~2;
#> rx_lambda_~1;
#> rx_hi_~1;
#> rx_low_~0;
#> rx_expr_0~ETA[2]+THETA[2];
#> rx_expr_1~ETA[3]+THETA[3];
#> rx_expr_2~ETA[1]+THETA[1];
#> rx_expr_3~exp(rx_expr_0);
#> rx_expr_4~exp(rx_expr_1);
#> rx_expr_5~exp(rx_expr_2);
#> rx_pred_=linCmtB(rx__PTR__,t,0,1,1,0,rx_expr_3,rx_expr_4,0,0,0,0,0,1,0,0,rx_expr_5,0,1,0,0);
#> rx_r_=((THETA[4])*(THETA[4]));
#> tka=THETA[1];
#> tcl=THETA[2];
#> tv=THETA[3];
#> add.sd=THETA[4];
#> eta.ka=ETA[1];
#> eta.cl=ETA[2];
#> eta.v=ETA[3];
#> vx=v;
#> ka=rx_expr_5;
#> cl=rx_expr_3;
#> v=rx_expr_4;
#> vx=rx_expr_4;
#> tad=tad();
#> dosenum=dosenum();
#> Error in rxSolveSEXP(object, .ctl, .nms, .xtra, params, events, inits, : The following parameter(s) are required for solving: v
```

<sup>Created on 2020-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattfidler** [comment] 2020-09-09 23:11
I can reproduce this on the latest:

<details>

``` r
library(nlmixr)

one.cmt <- function() {
  ini({
    ## You may label each parameter with a comment
    tka <- 0.45 # Log Ka
    tcl <- 1 # Log Cl
    ## This works with interactive models
    ## You may also label the preceding line with label("label text")
    tv <- 3.45; label("log V")
    ## the label("Label name") works with all models
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    vx <- v
    linCmt() ~ add(add.sd)
  })
}

one.cmt_u <- update(one.cmt)
#> ℹ parameter labels from comments will be replaced by 'label()'

fit <- nlmixr(one.cmt, theo_sd, est="focei", control=foceiControl(print=0))
#> ℹ parameter labels from comments will be replaced by 'label()'
#> → creating full model...
#> → pruning branches (`if`/`else`)...
#> ✔ done
#> → loading into symengine environment...
#> ✔ done
#> → creating full model...
#> → pruning branches (`if`/`else`)...
#> ✔ done
#> → loading into symengine environment...
#> ✔ done
#> → calculate jacobian
#> → calculate ∂(f)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → calculate ∂(R²)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → finding duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → optimizing duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → optimizing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → compiling inner model...
#> ✔ done
#> → compiling EBE model...
#> ✔ done
#> RxODE 0.9.2.0 using 4 threads (see ?getRxThreads)
#> calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00 
#> done
#> Calculating residuals/tables
#> Model:
#> 
#> rx_yj_~2;
#> rx_lambda_~1;
#> rx_hi_~1;
#> rx_low_~0;
#> rx_expr_0~ETA[2]+THETA[2];
#> rx_expr_1~ETA[3]+THETA[3];
#> rx_expr_2~ETA[1]+THETA[1];
#> rx_expr_3~exp(rx_expr_0);
#> rx_expr_4~exp(rx_expr_1);
#> rx_expr_5~exp(rx_expr_2);
#> rx_pred_=linCmtB(rx__PTR__,t,0,1,1,0,rx_expr_3,rx_expr_4,0,0,0,0,0,1,0,0,rx_expr_5,0,1,0,0);
#> rx_r_=((THETA[4])*(THETA[4]));
#> tka=THETA[1];
#> tcl=THETA[2];
#> tv=THETA[3];
#> add.sd=THETA[4];
#> eta.ka=ETA[1];
#> eta.cl=ETA[2];
#> eta.v=ETA[3];
#> vx=v;
#> ka=rx_expr_5;
#> cl=rx_expr_3;
#> v=rx_expr_4;
#> vx=rx_expr_4;
#> tad=tad();
#> dosenum=dosenum();
#> Error in rxSolveSEXP(object, .ctl, .nms, .xtra, params, events, inits, : The following parameter(s) are required for solving: v
```

<sup>Created on 2020-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

Perhaps this will go away with a single model... unsure.

**Comment by mattfidler** [comment] 2020-09-10 21:12
This also seems to be fixed by the single model fixes

``` r
library(nlmixr)

one.cmt <- function() {
  ini({
    ## You may label each parameter with a comment
    tka <- 0.45 # Log Ka
    tcl <- 1 # Log Cl
    ## This works with interactive models
    ## You may also label the preceding line with label("label text")
    tv <- 3.45; label("log V")
    ## the label("Label name") works with all models
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    vx <- v
    linCmt() ~ add(add.sd)
  })
}

one.cmt_u <- update(one.cmt)
#> ℹ parameter labels from comments will be replaced by 'label()'
class(one.cmt_u)
#> [1] "nlmixrUI"
fit <- nlmixr(one.cmt, theo_sd, est="focei", control=foceiControl(print=0))
#> ℹ parameter labels from comments will be replaced by 'label()'
#> singleOde
#> → creating full model...
#> → pruning branches (`if`/`else`)...
#> ✔ done
#> → loading into symengine environment...
#> ✔ done
#> → creating full model...
#> → pruning branches (`if`/`else`)...
#> ✔ done
#> → loading into symengine environment...
#> ✔ done
#> → calculate jacobian
#> → calculate ∂(f)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → calculate ∂(R²)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → finding duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → optimizing duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → optimizing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → compiling inner model...
#> ✔ done
#> → compiling EBE model...
#> ✔ done
#> RxODE 0.9.2.0 using 4 threads (see ?getRxThreads)
#> calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00 
#> done
#> Calculating residuals/tables
#> done.
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : initial ETAs were nudged; (can control by foceiControl(etaNudge=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod
#> = FALSE, : ETAs were reset to zero during optimization; (Can control by
#> foceiControl(resetEtaP=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : gradient problems with initial estimate and covariance; see $scaleInfo
```

<sup>Created on 2020-09-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Closed by mattfidler** 2020-09-10 21:12 UTC
