### ISSUE TITLE
Can't pass control as an argument to nlmixr within a function

### ISSUE THREAD

**Issue by tamas-ferenci** [nlmixrdevelopment/nlmixr#201] opened 2019-07-16 21:38 UTC
It seems pretty mysterious, but for some reason, this doesn't work:

```
foo <- function( fit, incontrol = list( print = 0 ) ) {
  nlmixr( fit, theo_sd, est = "saem", control = incontrol )
}

fit2 <- nlmixr( one.compartment.saem, theo_sd, est = "saem" )
foo( fit2 )
```

I can't imagine what could have gone wrong here (or I am overlooking something trivial?).

This is what I get:
```
> foo( fit2 )
Error in base::serialize(object, connection = NULL, ascii = ascii, version = serializeVersion) :
object 'incontrol' not found
Called from: base::serialize(object, connection = NULL, ascii = ascii, version = serializeVersion)
Browse[1]> Q
```

**Comment by mattfidler** [comment] 2019-07-20 03:02
I can reproduce the issue. I'm not sure of a work-around.  It has something to do with lazy evaluation.

**Comment by mattfidler** [comment] 2019-07-20 03:04
It could be due to the `do.call` that is dispatched.

**Comment by mattfidler** [comment] 2019-07-20 03:07
Indeed if you directly call the low level function, everything works as expected

``` r
library(nlmixr)
one.compartment <- function() {
    ini({
        tka <- 0.45 # Log Ka
        tcl <- 1 # Log Cl
        tv <- 3.45    # Log V
        eta.ka ~ 0.6
        eta.cl ~ 0.3
        eta.v ~ 0.1
        add.err <- 0.7
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl + eta.cl)
        v <- exp(tv + eta.v)
        d/dt(depot) = -ka * depot
        d/dt(center) = ka * depot - cl / v * center
        cp = center / v
        cp ~ add(add.err)
    })
}

foo <- function( fit, incontrol) {
    if (missing(incontrol)) incontrol <- list( print = 0 )
    nlmixr:::nlmixr_fit0(fit, theo_sd, est="saem", control=incontrol)
}

## fit2 <- nlmixr( one.compartment, theo_sd, est = "saem" )
uif <- nlmixr(one.compartment)
print(foo( uif ))
#> Compiling RxODE equations...done.
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====
#> Creating full model...done.
#> Pruning branches...done.
#> Loading into symengine environment...done.
#> Creating full model...done.
#> Pruning branches...done.
#> Loading into symengine environment...done.
#> Calculate Jacobian
#> [====|====|====|====|====|====|====|====|====|====
#> Calculate Sensitivites
#> [====|====|====|====|====|====|====|====|====|====
#> Finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====
#> Replacing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====
#> Compiling EBE model...done
#> Calculating residuals/tables
#> done.
#> ── nlmixr SAEM(ODE); OBJF not calculated fit ────────────────────────────── 
#>  Gaussian/Laplacian Likelihoods: AIC() or $objf etc. 
#>  FOCEi CWRES & Likelihoods: addCwres() 
#> 
#> ── Time (sec; $time): ───────────────────────────────────────────────────── 
#>   saem    setup table covariance
#>  3.204 1.311233 0.007      0.006
#> 
#> ── Population Parameters ($parFixed or $parFixedDf): ──────────────────────
#> Registered S3 method overwritten by 'R.oo':
#>   method        from       
#>   throw.default R.methodsS3
#>         Parameter  Est.     SE %RSE Back-transformed(95%CI) BSV(CV%)
#> tka        Log Ka 0.451  0.196 43.5       1.57 (1.07, 2.31)     71.9
#> tcl        Log Cl  1.02 0.0836 8.22       2.77 (2.35, 3.26)     27.0
#> tv          Log V  3.45 0.0469 1.36       31.5 (28.7, 34.5)     14.0
#> add.err           0.692                               0.692         
#>         Shrink(SD)%
#> tka         0.411% 
#> tcl          3.36% 
#> tv           10.0% 
#> add.err             
#> 
#>   Covariance Type ($covMethod): linFim
#>   No correlations in between subject variability (BSV) matrix
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs) 
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink 
#> 
#> ── Fit Data (object is a modified tibble): ──────────────────────────────── 
#> # A tibble: 132 x 18
#>   ID     TIME    DV  EVID  PRED    RES IPRED   IRES  IWRES eta.ka eta.cl
#>   <fct> <dbl> <dbl> <int> <dbl>  <dbl> <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
#> 1 1     0      0.74     0  0     0.74   0     0.74   1.07   0.105 -0.487
#> 2 1     0.25   2.84     0  3.26 -0.423  3.86 -1.02  -1.48   0.105 -0.487
#> 3 1     0.570  6.57     0  5.84  0.725  6.81 -0.235 -0.340  0.105 -0.487
#> # … with 129 more rows, and 7 more variables: eta.v <dbl>, ka <dbl>,
#> #   cl <dbl>, v <dbl>, cp <dbl>, depot <dbl>, center <dbl>
```

<sup>Created on 2019-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattfidler** [comment] 2019-07-20 03:11
In the `do.call` I will probably need to specify the environment as `parent.frame(2)` or something similar.

**Comment by mattfidler** [comment] 2019-07-20 03:17
Indeed using an `envir` seems to fix this

Let me know if it works for you.  I will close it for now.

Here are my results

<details>
``` r
library(nlmixr)
one.compartment <- function() {
    ini({
        tka <- 0.45 # Log Ka
        tcl <- 1 # Log Cl
        tv <- 3.45    # Log V
        eta.ka ~ 0.6
        eta.cl ~ 0.3
        eta.v ~ 0.1
        add.err <- 0.7
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl + eta.cl)
        v <- exp(tv + eta.v)
        d/dt(depot) = -ka * depot
        d/dt(center) = ka * depot - cl / v * center
        cp = center / v
        cp ~ add(add.err)
    })
}

foo <- function( fit, incontrol) {
    if (missing(incontrol)) incontrol <- list( print = 0 )
    nlmixr(fit, theo_sd, est="saem", control=incontrol)
}

## fit2 <- nlmixr( one.compartment, theo_sd, est = "saem" )
uif <- nlmixr(one.compartment)
print(foo( uif ))
#> Compiling RxODE equations...done.
#> Building SAEM model...done
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====
#> Creating full model...done.
#> Pruning branches...done.
#> Loading into symengine environment...done.
#> Creating full model...done.
#> Pruning branches...done.
#> Loading into symengine environment...done.
#> Calculate Jacobian
#> [====|====|====|====|====|====|====|====|====|====
#> Calculate Sensitivites
#> [====|====|====|====|====|====|====|====|====|====
#> Finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====
#> Replacing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====
#> Compiling EBE model...done
#> Calculating residuals/tables
#> done.
#> ── nlmixr SAEM(ODE); OBJF not calculated fit ────────────────────────────── 
#>  Gaussian/Laplacian Likelihoods: AIC() or $objf etc. 
#>  FOCEi CWRES & Likelihoods: addCwres() 
#> 
#> ── Time (sec; $time): ───────────────────────────────────────────────────── 
#>          saem    setup table covariance    other
#> elapsed 18.51 1.589438 0.007      0.006 0.054562
#> 
#> ── Population Parameters ($parFixed or $parFixedDf): ──────────────────────
#> Registered S3 method overwritten by 'R.oo':
#>   method        from       
#>   throw.default R.methodsS3
#>         Parameter  Est.     SE %RSE Back-transformed(95%CI) BSV(CV%)
#> tka        Log Ka 0.451  0.196 43.5       1.57 (1.07, 2.31)     71.9
#> tcl        Log Cl  1.02 0.0836 8.22       2.77 (2.35, 3.26)     27.0
#> tv          Log V  3.45 0.0469 1.36       31.5 (28.7, 34.5)     14.0
#> add.err           0.692                               0.692         
#>         Shrink(SD)%
#> tka         0.411% 
#> tcl          3.36% 
#> tv           10.0% 
#> add.err             
#> 
#>   Covariance Type ($covMethod): linFim
#>   No correlations in between subject variability (BSV) matrix
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs) 
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink 
#> 
#> ── Fit Data (object is a modified tibble): ──────────────────────────────── 
#> # A tibble: 132 x 18
#>   ID     TIME    DV  EVID  PRED    RES IPRED   IRES  IWRES eta.ka eta.cl
#>   <fct> <dbl> <dbl> <int> <dbl>  <dbl> <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
#> 1 1     0      0.74     0  0     0.74   0     0.74   1.07   0.105 -0.487
#> 2 1     0.25   2.84     0  3.26 -0.423  3.86 -1.02  -1.48   0.105 -0.487
#> 3 1     0.570  6.57     0  5.84  0.725  6.81 -0.235 -0.340  0.105 -0.487
#> # … with 129 more rows, and 7 more variables: eta.v <dbl>, ka <dbl>,
#> #   cl <dbl>, v <dbl>, cp <dbl>, depot <dbl>, center <dbl>
```

<sup>Created on 2019-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
</details>

**Closed by mattfidler** 2019-07-20 03:17 UTC

**Comment by tamas-ferenci** [comment] 2019-07-22 06:40
Works perfectly, thank you very much!
