### ISSUE TITLE
Docker installation documentation needs improvement and Docker nlmixr has errors

### ISSUE THREAD

**Issue by nholford** [nlmixrdevelopment/nlmixr#71] opened 2018-08-20 12:00 UTC
1. The [Docker installation instructions](https://nlmixrdevelopment.github.io/nlmixr_bookdown/install.html#installation-via-docker) 
should say that the Windows container version should NOT be installed. I installed the Windows version on Windows 10 Pro then found that nlmixr would not install unless it was the Linux container version.  The Task bar Docker icon indicates the container type can be switched to Linux from but this failed because "your Windows version is not compatible". So I had to uninstall Docker, install it without asking for the Windows version, re-download a load of stuff and finally install nlmixr from a Linux container (big waste of time).
[rundocker_log.txt](https://github.com/nlmixrdevelopment/nlmixr/files/2302189/rundocker_log.txt)

2. There are no instructions on how to test nlmixr with the Docker installation.  This may be obvious to the developer but not to someone who has never used Docker nor nlmixr.

3. I found the example.R and theoph.R scripts in /examples and tried running them. Both produced extensive errors. See these files.

[example_R_errors.txt](https://github.com/nlmixrdevelopment/nlmixr/files/2302214/example_R_errors.txt)

[theoph_R_errors.txt](https://github.com/nlmixrdevelopment/nlmixr/files/2302196/theoph_R_errors.txt)

4. Has anybody got the Docker installation method to run nlmixr recently?

**Comment by mattfidler** [comment] 2018-08-20 13:05
Hi Nik, I have tested the docker on Linux and it seemed to run for me.  Others have tested Mac.  I'm unsure how many people have tested windows.

@RichardHooijmaijers @kestrel99 have you looked into Windows docker running?  I don't have admin access so I cannot install/test any docker installs.

**Comment by RichardHooijmaijers** [comment] 2018-08-21 08:30
I tested the docker container only on Mac, the assumption is that the container itself is platform independent. Not sure if @kestrel99 had the opportunity to test it, otherwise I can check if I can access a win10 machine.

**Comment by RichardHooijmaijers** [comment] 2018-08-21 08:41
After reviewing the attached errors, I think the problem might be caused by a permission issue. The working directory is set to the examples directory which has no write permissions. Could you please test the code without setting the working directory (or set it to a local drive that is mounted in the docker command)?
I will look into the installation documentation to make things more clear and to include testing instructions

**Comment by nholford** [comment] 2018-08-21 10:25
Thanks @RichardHooijmaijers for a very plausible explanation for the errors. 

The documentation says I can mount my own working directory with this kind of command: 
" In the following example the folder /Users/richard/Document on the host computer will be mounted to the docs folder in the /home/rstudio directory of the container"
docker run -v /Users/richard/Documents/:/home/rstudio/docs -d -p 8787:8787 nlmixr/nlmixr:1.0

I changed your example to run docker:
docker run -v /Users/nholf/Documents/:/home/rstudio/docs -d -p 8787:8787 nlmixr/nlmixr:1.0
but I could not find the files in /Users/nholf/Documents in the /home/rtudio/docs folder. Can you suggest why this is not working?

 I could not find a way to make this version of Rstudio find my Windows folders using either the files or set working directory menus because I cannot move away from the "~" home directory. 

After restarting Windows for an unrelated reason I tried to restart the Rstudio session but kept getting this error message:

This site can’t be reached
localhost refused to connect.
Search Google for localhost 8787
ERR_CONNECTION_REFUSED

It took me a while before I realized I needed to execute the docker command every time I restarted Docker. Although Docker is restarted and I am logged in to Docker when I restart Windows it is not obvious that I need to re-run the docker command again. I suggest you explain this is in your documentation.

**Comment by RichardHooijmaijers** [comment] 2018-08-21 11:16
The example in the documentation for mounting drives is based on linux/mac systems. The same should be possible in windows but the form would be a bit different, e.g.:
docker run -v c:/Users/nholf:/home/rstudio/docs -d -p 8787:8787 nlmixr/nlmixr:1.0
This will mount the local folder (and all subfolders!) "c:\Users\nholf" to the docs folder within Rstudio. I think in your case it is not possible to see the windows folders as the mounted folder is not found. 
Furthermore I read that in certain cases it might be necessary to enable drives for mounting. This can be done in the settings of docker, in the "file sharing" section

I will take all your suggestions into account when updating the documentation.

**Comment by nholford** [comment] 2018-08-21 13:33
Thanks @RichardHooijmaijers for advice on how to access local directories specified in the docker run command.

After some experimentation I found that on Windows the following steps are necessary to mount local directories. 
1. Go to Docker settings shared drives and enter a local drive letter e.g. C. . This then requires providing login credentials for your local device to validate the choice of drive. That requirement meant I had to set up a local account on Windows instead of the Microsoft account I had been using.
2. Enter the drive letter and a colon e.g. C: before the path to the local directories.  The trailing path separator is optional. It works with or without the "/".
3. Including the /home/rstudio/docs path seems to be essential in order to have access to the local directories (in /home/rstudio/docs).

`docker run -v C:/Users/nholf/Documents:/home/rstudio/docs -d -p 8787:8787 nlmixr/nlmixr:1.0
`

I note I now have access to other directories in /home/rstudio in addition to examples and kitematic (i.e. analysis, data, models, scripts, ShinyMixR).

I'll provide a separate comment on running the example.R and theoph.R scripts.

**Comment by RichardHooijmaijers** [comment] 2018-09-28 06:42
Just wanted to let you know that the new docker is online based on the latest CRAN versions of nlmixr/RxODE. 
I also adapted the documentation and taken all your suggestions into account. Please let us know if you are missing something or if things do not work as expected.

**Comment by RichardHooijmaijers** [comment] 2018-09-28 06:43
Attached the link to the latest version:
[https://github.com/nlmixrdevelopment/nlmixr/releases/tag/v1.0.0-7](https://github.com/nlmixrdevelopment/nlmixr/releases/tag/v1.0.0-7)

**Comment by mattfidler** [comment] 2019-05-23 14:34
I think there is a new docker github website, so for now I'm closing this issue.

https://github.com/RichardHooijmaijers/nlmixr.docker

**Closed by mattfidler** 2019-05-23 14:34 UTC
