### ISSUE TITLE
1.1.0-1 installer version of nlmixr: Hard coded directory causes failure of nlmixr

### ISSUE THREAD

**Issue by nholford** [nlmixrdevelopment/nlmixr#147] opened 2019-04-10 11:06 UTC
I’ve tried out the 1.1.0-1 installer. It seems Matt's own user directory has been hardcoded so the code fails when trying to run nlmixr (see error below).

> pk.fit.ka1t <- nlmixr(one.compartment.saem, data.pk,  est="saem", control=saemControl(print=100000))
Error in file(file, if (append) "a" else "w") : 
  cannot open the connection
In addition: Warning messages:
1: In dir.create(.tmp, recursive = TRUE) :
  cannot create dir 'C:\Users\fidlema3', reason 'Permission denied'
2: In file(file, if (append) "a" else "w") :
  cannot open file 'C:\Users\fidlema3\AppData\Local\Temp\1\ep\Rtmp4gJS7H/ui-9e46bcabae020185a639340e7a5a7617.lock': No such file or directory

**Comment by mattfidler** [comment] 2019-04-10 14:57
I think this is caused by compilation on my side.  I'm unsure, of course, so I will release another installer and you can let me know that it works (hopefully).

**Comment by mattfidler** [comment] 2019-04-10 22:44
In theory this should be addressed in the following installer

https://github.com/nlmixrdevelopment/nlmixr/releases/download/v1.1.0-2/nlmixr_1.1.0-2_x86_64_install.exe

Unfortunately, my computer is still the same, so I cannot actually test my hypothesis here.

**Comment by mattfidler** [comment] 2019-04-11 03:15
Fixed bug, can run tutorial;  Use

https://github.com/nlmixrdevelopment/nlmixr/releases/download/v1.1.0-3/nlmixr_1.1.0-3_x86_64_install.exe

**Comment by nholford** [comment] 2019-04-11 09:25
Thanks for the 1.1.0-3 installer.
I tried using it from the Windows command line (Windows Server 2012). Rterm.exe crashed because Python could not find UTF-8 encoding mode.

![image](https://user-images.githubusercontent.com/26332480/55942501-c5f1cb00-5c44-11e9-8dbe-32a69f22b3a7.png)

**Comment by mattfidler** [comment] 2019-04-12 02:13
I believe this must be fixed.

**Closed by mattfidler** 2019-04-12 02:13 UTC
