### ISSUE TITLE
nlmixr focei solver crashes R (fatal error)

### ISSUE THREAD

**Issue by mayerbry** [nlmixrdevelopment/nlmixr#87] opened 2018-10-13 01:18 UTC
I have some data that crashes R when I use the focei solver. Unfortunately, there is no error message produced by the function. Below is a a reproducible example (for my machine) that always crashes at the 33rd iteration, a screenshot of the error, and my R session info. If any ID is removed from that example, it runs fine. I'm using RStudio, but R console also crashes. Happy to provide other information that might help.

Potentially reproducible example:

```
library(nlmixr)

my2CptModel <- function() {
  ini({
    tv1 <- log(4.5)
    tcl <- log(0.25)
    tv2  <- log(3.28)
    tq   <- log(0.67)
    eta.cl ~ 1
    eta.v1 ~ 1
    eta.v2 ~ 1
    eta.q ~ 1
    prop.err <- 0.1534
  })
  model({
    cl <- exp(tcl + eta.cl)
    v1 <- exp(tv1 + eta.v1)
    v2 <- exp(tv2 + eta.v2)
    q  <- exp(tq + eta.q)
    linCmt() ~ prop(prop.err)

  })
}

test_data = structure(list(ID = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 4L, 4L, 4L, 4L, 4L, 4L, 
4L, 4L, 4L, 4L, 4L, 4L, 4L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L), TIME = c(0, 0.0416666666666667, 
0.041667, 0.0625, 0.16667, 0.29167, 0.41667, 0.54167, 1, 2, 4, 
7, 14, 21, 28, 42, 56, 0, 0.0416666666666667, 0.041667, 0.0625, 
0.16667, 0.29167, 0.41667, 0.54167, 1, 2, 4, 7, 14, 22, 28, 44, 
58, 84, 127, 0, 0.0416666666666667, 0.041667, 0.0625, 0.16667, 
0.29167, 0.41667, 0.54167, 7, 14, 21, 28, 42, 56, 85, 113, 0, 
0.041667, 0.0416672410228134, 0.0625, 0.16667, 0.29167, 0.41667, 
0.54167, 1, 2, 4, 7, 14, 0, 0.0416666666666667, 0.041667, 0.0625, 
0.16667, 0.29167, 0.41667, 0.54167, 1, 2, 4, 7, 14, 21, 28, 43, 
58, 84), DV = c(0, 0, 409.47, 399.67, 336.97, 262.77, 286.97, 
300.67, 256.87, 203.77, 122.97, 66.27, 24.67, 12.57, 4.38, 1.2, 
0.27, 0, 0, 89.9, 73.7, 77.5, 80.1, 75, 74.5, 49.5, 34.5, 18, 
15.94, 13.58, 10.71, 7.53, 4.33, 3.13, 1.77, 0.5, 0, 0, 243.4, 
195.3, 128.6, 117.9, 100.5, 93.9, 17.63, 15.12, 14.09, 8.53, 
6, 4.16, 1.69, 0.98, 0, 176.72, 0, 142.72, 103.52, 108.72, 88.62, 
69.82, 57.82, 37.42, 24.12, 29.52, 9.02, 0, 0, 81.1, 67.3, 48.7, 
90.1, 58.3, 66.2, 50.6, 30.6, 21.8, 12.6, 12.1, 10.81, 4.82, 
2.21, 1.47, 0.56), AMT = c(46800, -46800, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 5796, -5796, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 4320, -4320, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 14509, 0, -14509, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 9489.6, -9489.6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0), RATE = c(46800, -46800, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 5796, -5796, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 4320, -4320, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 14509, 0, -14509, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
9489.6, -9489.6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0), EVID = c(10101, 10101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 10101, 10101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 10101, 10101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 10101, 0, 10101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10101, 10101, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)), row.names = c(1L, 
2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L, 13L, 14L, 15L, 
16L, 17L, 18L, 19L, 20L, 21L, 22L, 23L, 24L, 25L, 26L, 27L, 28L, 
29L, 30L, 31L, 32L, 33L, 34L, 35L, 36L, 37L, 38L, 39L, 40L, 41L, 
42L, 43L, 44L, 45L, 46L, 47L, 48L, 49L, 50L, 51L, 52L, 55L, 56L, 
57L, 58L, 59L, 60L, 61L, 62L, 63L, 64L, 65L, 66L, 67L, 68L, 69L, 
70L, 71L, 72L, 73L, 74L, 75L, 76L, 77L, 78L, 79L, 80L, 81L, 82L, 
83L, 84L, 85L), class = "data.frame")

res = nlmixr(my2CptModel, test_data, est = "focei")
```

![focei_crash](https://user-images.githubusercontent.com/39173901/46899551-999df300-ce49-11e8-90fb-aae9ae0fc1bb.png)

Session Info: 
```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nlmixr_1.0.0-7

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.19              pillar_1.3.0              compiler_3.5.1            plyr_1.8.4               
 [5] bindr_0.1.1               PreciseSums_0.3           tools_3.5.1               mvnfast_0.2.5            
 [9] digest_0.6.18             memoise_1.1.0             tibble_1.4.2              gtable_0.2.0             
[13] nlme_3.1-137              lattice_0.20-35           pkgconfig_2.0.2           rlang_0.2.2              
[17] rex_1.1.2                 rstudioapi_0.7            yaml_2.2.0                parallel_3.5.1           
[21] RcppArmadillo_0.9.100.5.0 bindrcpp_0.2.2            n1qn1_6.0.1-3             dplyr_0.7.6              
[25] lbfgs_1.2.1               grid_3.5.1                tidyselect_0.2.4          glue_1.3.0               
[29] R6_2.3.0                  ggplot2_3.0.0             purrr_0.2.5               dparser_0.1.8            
[33] magrittr_1.5              vpc_1.1.0                 scales_1.0.0              assertthat_0.2.0         
[37] RxODE_0.8.0-8             colorspace_1.3-2          brew_1.0-6                lazyeval_0.2.1           
[41] munsell_0.5.0             crayon_1.3.4    
```

Note: subsets of the data seem to run fine:
```
purrr::walk(1:5, function(i){
  print(i)
  nlmixr(my2CptModel, subset(test_data, ID != i), est = "focei")
})
```

**Comment by mattfidler** [comment] 2018-10-13 23:09
Thank you for the reproducable example @mayerbry it makes it easy to run.

My guess is the covariance step is causing the crash.  You can test this by:

```R
res <- nlmixr(my2CptModel, test_data, est = "focei", foceiControl(covMethod=""))
```
to skip the covariance step. If it runs, then it fits.

I do not have access to a Mac yet.

**Comment by mattfidler** [comment] 2018-10-13 23:10
On the development branch this runs without crashing, but the covariance method changed to be a bit more accurate and may have inadvertantly fixed the crash.

**Comment by mattfidler** [comment] 2018-10-13 23:39
My guess is a `clang`/mac vs `gcc`/linux or windows difference.

The last error we see is most likely at:

https://github.com/nlmixrdevelopment/RxODE/blob/26e1d89bdd1c1b1d9833f883cbc5e94c818be744/src/lsoda.c#L897

Which is a C-based error. When/if I get a mac I will look into this issue some more.

The python piece occurs at the beginning and should give the same results regardless of the platform.

**Comment by mattfidler** [comment] 2018-10-13 23:41
I will also revert to this version to see if I can reproduce on linux

**Comment by mattfidler** [comment] 2018-10-14 00:40
Unfortunately, I cannot reproduce the issue under Linux....

**Comment by mattfidler** [comment] 2018-11-13 21:42
@mayerbry did you ever figure this out?

**Comment by mayerbry** [comment] 2018-11-13 21:49
I think it's an error specific to my machine that is generated during the communication between R and C. I also get crashes when there are data bugs (for example, I once made a serious mistake coding EVID) that affect the solver.

I was going to suggest you close the issue but was also waiting to see if maybe someone else had a similar problem. I'll leave it up to you.

**Comment by mattfidler** [comment] 2019-01-23 19:19
I"m going to close the issue.

**Closed by mattfidler** 2019-01-23 19:19 UTC

**Comment by sueinchoi** [comment] 2019-10-14 03:53
I'm using mac computer and having identical problem..
whenever i use the 'focei' method, R session aborts.

Was there any update to solve this problem?

**Comment by mattfidler** [comment] 2019-10-15 04:22
Could you provide the sessioninformation, that is:
``` r
library(nlmixr); sessionInfo();
#> R version 3.6.0 (2019-04-26)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Gentoo/Linux
#> 
#> Matrix products: default
#> BLAS:   /usr/lib64/libblas.so.3.8.0
#> LAPACK: /usr/lib64/liblapack.so.3.8.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.utf8       LC_NUMERIC=C             
#>  [3] LC_TIME=en_US.utf8        LC_COLLATE=en_US.utf8    
#>  [5] LC_MONETARY=en_US.utf8    LC_MESSAGES=en_US.utf8   
#>  [7] LC_PAPER=en_US.utf8       LC_NAME=C                
#>  [9] LC_ADDRESS=C              LC_TELEPHONE=C           
#> [11] LC_MEASUREMENT=en_US.utf8 LC_IDENTIFICATION=C      
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] nlmixr_1.1.1-3
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.2                compiler_3.6.0           
#>  [3] pillar_1.4.2              highr_0.8                
#>  [5] PreciseSums_0.3           tools_3.6.0              
#>  [7] mvnfast_0.2.5             digest_0.6.21            
#>  [9] nlme_3.1-139              lattice_0.20-38          
#> [11] huxtable_4.7.0            memoise_1.1.0            
#> [13] evaluate_0.14             tibble_2.1.3             
#> [15] gtable_0.3.0              pkgconfig_2.0.3          
#> [17] rlang_0.4.0               parallel_3.6.0           
#> [19] yaml_2.2.0                xfun_0.10                
#> [21] RcppArmadillo_0.9.800.1.0 n1qn1_6.0.1-3            
#> [23] stringr_1.4.0             dplyr_0.8.3              
#> [25] knitr_1.25                lbfgs_1.2.1              
#> [27] generics_0.0.2            grid_3.6.0               
#> [29] tidyselect_0.2.5          glue_1.3.1               
#> [31] R6_2.4.0                  rmarkdown_1.16           
#> [33] polyclip_1.10-0           dparser_1.3.1-0          
#> [35] ggplot2_3.2.1             purrr_0.3.2              
#> [37] tweenr_1.0.1              farver_1.1.0             
#> [39] magrittr_1.5              vpc_1.1.0                
#> [41] units_0.6-5               scales_1.0.0             
#> [43] htmltools_0.4.0           MASS_7.3-51.4            
#> [45] assertthat_0.2.1          ggforce_0.3.1            
#> [47] RxODE_0.9.1-7             colorspace_1.4-1         
#> [49] brew_1.0-6                stringi_1.4.3            
#> [51] lotri_0.1.1               lazyeval_0.2.2           
#> [53] munsell_0.5.0             crayon_1.3.4
```

<sup>Created on 2019-10-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattfidler** [comment] 2019-10-15 04:23
Often these crashes come from incompatible versions of RxODE/nlmixr
